### ISSUE TITLE
Missing Node Types When loading the graph, the following node types were not found

### ISSUE THREAD

**Issue by GrenKain** [yolain/ComfyUI-Easy-Use#646]
Help
I tried to install different versions, nothing helps.

![Image](https://github.com/user-attachments/assets/79c55cc1-83b3-456d-bda3-314530fe2c91)

**Comment by GrenKain** [comment]
The problem is with the new version of Comfy UI, nodes often stop working because of it, install the older version.

I have installed this version, everything is working fine now.
https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.2.6

**Comment by yolain** [comment]
Without boot log information, I'm having a hard time troubleshooting the cause of the issue.

Easyuse usually keeps up with the version of the main ComfyUI core, and I'm using the latest version of the ComfyUI core locally, and it works fine.

**Comment by JXYS28** [comment]
Here is the error message I got when I update comfy to v0.3.13.

`Error message occurred while importing the 'ComfyUI-Easy-Use' module.

Traceback (most recent call last):
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\peft.py", line 38, in <module>
    from .lora_base import _fetch_state_dict, _func_optionally_disable_offloading
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\lora_base.py", line 56, in <module>
    from peft.tuners.tuners_utils import BaseTunerLayer
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\mapping.py", line 25, in <module>
    from .mixed_model import PeftMixedModel
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\mixed_model.py", line 29, in <module>
    from .peft_model import PeftModel
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\peft_model.py", line 37, in <module>
    from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel
ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' (E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2112, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use\__init__.py", line 21, in <module>
    imported_module = importlib.import_module(".py.{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use\py\easyNodes.py", line 17, in <module>
    from .layer_diffuse import LayerDiffuse, LayerMethod
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use\py\layer_diffuse\__init__.py", line 12, in <module>
    from .model import ModelPatcher, TransparentVAEDecoder, calculate_weight_adjust_channel
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use\py\layer_diffuse\model.py", line 23, in <module>
    from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\unets\__init__.py", line 6, in <module>
    from .unet_2d import UNet2DModel
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\unets\unet_2d.py", line 24, in <module>
    from .unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\unets\unet_2d_blocks.py", line 36, in <module>
    from ..transformers.dual_transformer_2d import DualTransformer2DModel
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\transformers\__init__.py", line 6, in <module>
    from .cogvideox_transformer_3d import CogVideoXTransformer3DModel
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\transformers\cogvideox_transformer_3d.py", line 22, in <module>
    from ...loaders import PeftAdapterMixin
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.loaders.peft because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\__init__.py)

Close



Manager




Show Image Feed 🐍
1

Idle
↹ Resize Feed
Feed Size...

Column count...

Clear
❌
`

**Comment by yolain** [comment]
> Here is the error message I got when I update comfy to v0.3.13.
> 
> `Error message occurred while importing the 'ComfyUI-Easy-Use' module.
> 
> Traceback (most recent call last): File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module return importlib.import_module("." + module_name, self.**name**) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "importlib__init__.py", line 126, in import_module File "", line 1204, in _gcd_import File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\peft.py", line 38, in from .lora_base import _fetch_state_dict, _func_optionally_disable_offloading File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\lora_base.py", line 56, in from peft.tuners.tuners_utils import BaseTunerLayer File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft__init__.py", line 22, in from .auto import ( File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\auto.py", line 32, in from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\mapping.py", line 25, in from .mixed_model import PeftMixedModel File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\mixed_model.py", line 29, in from .peft_model import PeftModel File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\peft_model.py", line 37, in from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' (E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers__init__.py)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2112, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use__init__.py", line 21, in imported_module = importlib.import_module(".py.{}".format(module_name), **name**) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "importlib__init__.py", line 126, in import_module File "", line 1204, in _gcd_import File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use\py\easyNodes.py", line 17, in from .layer_diffuse import LayerDiffuse, LayerMethod File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use\py\layer_diffuse__init__.py", line 12, in from .model import ModelPatcher, TransparentVAEDecoder, calculate_weight_adjust_channel File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use\py\layer_diffuse\model.py", line 23, in from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\unets__init__.py", line 6, in from .unet_2d import UNet2DModel File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\unets\unet_2d.py", line 24, in from .unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\unets\unet_2d_blocks.py", line 36, in from ..transformers.dual_transformer_2d import DualTransformer2DModel File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\transformers__init_.py", line 6, in from .cogvideox_transformer_3d import CogVideoXTransformer3DModel File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\transformers\cogvideox_transformer_3d.py", line 22, in from ...loaders import PeftAdapterMixin File "", line 1229, in _handle_fromlist File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 910, in **getattr** module = self._get_module(self._class_to_module[name]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module raise RuntimeError( RuntimeError: Failed to import diffusers.loaders.peft because of the following error (look up to see its traceback): cannot import name 'EncoderDecoderCache' from 'transformers' (E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers__init__.py)_
> 
> Close
> 
> Manager
> 
> Show Image Feed 🐍 1
> 
> Idle ↹ Resize Feed Feed Size...
> 
> Column count...
> 
> Clear ❌ `

Update `peft` and `transfomers` dependencies.

**Comment by JXYS28** [comment]
> > Here is the error message I got when I update comfy to v0.3.13.
> > `Error message occurred while importing the 'ComfyUI-Easy-Use' module.
> > Traceback (most recent call last): File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module return importlib.import_module("." + module_name, self.**name**) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "importlib__init__.py", line 126, in import_module File "", line 1204, in _gcd_import File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\peft.py", line 38, in from .lora_base import _fetch_state_dict, _func_optionally_disable_offloading File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\lora_base.py", line 56, in from peft.tuners.tuners_utils import BaseTunerLayer File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft__init__.py", line 22, in from .auto import ( File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\auto.py", line 32, in from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\mapping.py", line 25, in from .mixed_model import PeftMixedModel File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\mixed_model.py", line 29, in from .peft_model import PeftModel File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\peft_model.py", line 37, in from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' (E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers__init__.py)
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last): File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2112, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use__init__.py", line 21, in imported_module = importlib.import_module(".py.{}".format(module_name), **name**) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "importlib__init__.py", line 126, in import_module File "", line 1204, in _gcd_import File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use\py\easyNodes.py", line 17, in from .layer_diffuse import LayerDiffuse, LayerMethod File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use\py\layer_diffuse__init__.py", line 12, in from .model import ModelPatcher, TransparentVAEDecoder, calculate_weight_adjust_channel File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use\py\layer_diffuse\model.py", line 23, in from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\unets__init__.py", line 6, in from .unet_2d import UNet2DModel File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\unets\unet_2d.py", line 24, in from .unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\unets\unet_2d_blocks.py", line 36, in from ..transformers.dual_transformer_2d import DualTransformer2DModel File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\transformers__init_.py", line 6, in from .cogvideox_transformer_3d import CogVideoXTransformer3DModel File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\transformers\cogvideox_transformer_3d.py", line 22, in from ...loaders import PeftAdapterMixin File "", line 1229, in _handle_fromlist File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 910, in **getattr** module = self._get_module(self._class_to_module[name]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module raise RuntimeError( RuntimeError: Failed to import diffusers.loaders.peft because of the following error (look up to see its traceback): cannot import name 'EncoderDecoderCache' from 'transformers' (E:\Programs\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers__init__.py)_
> > Close
> > Manager
> > Show Image Feed 🐍 1
> > Idle ↹ Resize Feed Feed Size...
> > Column count...
> > Clear ❌ `
> 
> Update `peft` and `transfomers` dependencies.

Thank you! This worked
